version: '3.8'

services:
  # The Mock HP Workstation Agent
  mock_z2_g9_agent:
    image: ubuntu:24.04
    container_name: simulated_z2_mini
    ports:
      - "1161:161/udp" # Host port 1161 map to container port 161
    volumes:
      # change file name to unique name to avoid lock
      - ./mock_snmpd.conf:/etc/snmp/custom_snmpd.conf
    command: >
      bash -c "apt-get update && apt-get install -y snmpd snmp && 
      snmpd -f -Lo -C -c /etc/snmp/custom_snmpd.conf"



  # The Central Monitoring/Verification Daemon

  snmp_receiver:
      image: ubuntu:24.04
      container_name: lab_snmp_receiver
      ports:
        - "1162:162/udp" # Host 1162 maps to Container 162
      volumes:
        # Endret målfilen til custom_snmptrapd.conf for å unngå dpkg-lås
        - ./snmptrapd.conf:/etc/snmp/custom_snmptrapd.conf
      command: >
        bash -c "apt-get update && apt-get install -y snmptrapd snmp && 
        snmptrapd -f -Lo -C -c /etc/snmp/custom_snmptrapd.conf"
